// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSrt7zdjoqTH7P5tQ5EPlPJR9YhX8oFjw',
    appId: '1:56498301287:web:63c6546f338fa1ecd067c2',
    messagingSenderId: '56498301287',
    projectId: 'trancend-prod',
    authDomain: 'trancend-prod.firebaseapp.com',
    databaseURL: 'https://trancend-prod.firebaseio.com',
    storageBucket: 'trancend-prod.appspot.com',
    measurementId: 'G-6QZ6J7TQ0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjMYCEqwl4YUXwZmVwVv_bhCaX1TYO0yQ',
    appId: '1:56498301287:android:76879284d117b144d067c2',
    messagingSenderId: '56498301287',
    projectId: 'trancend-prod',
    databaseURL: 'https://trancend-prod.firebaseio.com',
    storageBucket: 'trancend-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9V0VIG30nhc94n1lHqimDWZ050OHwQe8',
    appId: '1:56498301287:ios:2ff48ed91613d2a2d067c2',
    messagingSenderId: '56498301287',
    projectId: 'trancend-prod',
    databaseURL: 'https://trancend-prod.firebaseio.com',
    storageBucket: 'trancend-prod.appspot.com',
    androidClientId: '56498301287-236j0odq03ka0hg0q8dd9h4ba4fei1s5.apps.googleusercontent.com',
    iosClientId: '56498301287-n9fap30ltsqgpc046uamc0e41916m8uc.apps.googleusercontent.com',
    iosBundleId: 'app.trancend',
  );
}
