// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stage.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpy4JTVw7LB_jvO9Wm1ZnbBn39fxj-0Ks',
    appId: '1:782646386551:web:f2d6325f3da85096a54b72',
    messagingSenderId: '782646386551',
    projectId: 'trancend-stage',
    authDomain: 'trancend-stage.firebaseapp.com',
    storageBucket: 'trancend-stage.firebasestorage.app',
    measurementId: 'G-7KSW94ECLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBAnaFDK7gmS7GzMAe8bFZYbZJzvVP97s',
    appId: '1:782646386551:android:b18c748c8ab60c9ca54b72',
    messagingSenderId: '782646386551',
    projectId: 'trancend-stage',
    storageBucket: 'trancend-stage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7fq0jKzZ6rM4cK1i9hxhhDUNh5WMimfI',
    appId: '1:782646386551:ios:7d2e32f0e802ecafa54b72',
    messagingSenderId: '782646386551',
    projectId: 'trancend-stage',
    storageBucket: 'trancend-stage.firebasestorage.app',
    iosBundleId: 'app.trancend.stage',
  );
}
